41 drawing of simple shapes
JesseSwildens/Software-ontwikkeling-VESOFTON pull request #45
Opened 2024-05-28 12:39 UTC by JesseSwildens

2024-05-28 13:03 UTC, tomseli commented on app/Core/Inc/API_simpleShapes.h
API_simpleShapes does not adhere to snake_case

2024-05-28 13:04 UTC, Mirkoet commented on app/Core/Inc/API_simpleShapes.h
agree, minor spelling mistake. REQUEST CHANGES

2024-05-28 13:07 UTC, Mirkoet commented on app/Core/Src/API_simpleShapes.cpp
> +        API_setPixel(x + (cosf(angle) * radius), y + (sinf(angle) * radius), (uint8_t)color);
snake_case :)

2024-05-28 13:12 UTC, Mirkoet commented on app/Core/Src/API_simpleShapes.cpp
> +    VGA_RAM1[(y * VGA_DISPLAY_X) + x] = color;
`VGA_RAM1[(y * (VGA_DISPLAY_X + 1)) + x] = color;`

2024-05-28 13:13 UTC, Mirkoet commented on app/Core/Src/API_simpleShapes.cpp
> +    VGA_RAM1[(y * VGA_DISPLAY_X) + x] = color;
otherwise its not a circle

2024-05-28 13:14 UTC, Mirkoet commented on app/Core/Src/API_simpleShapes.cpp
> +        float angle = i * 2 * (PI / 100);
enable the FPU, maybe easier if it is done in this commit
`SCB->CPACR |= ((3UL << 10 * 2) | (3UL << 11 * 2));`

2024-05-28 13:16 UTC, Mirkoet commented on app/Core/Src/API_simpleShapes.cpp
> +int API_draw_circle(int x, int y, int radius, int color, int reserved)
This function is limited to a radius of 25 (which is really rather small). Bresenhams algorithm can be used to fix this issue

2024-05-28 13:17 UTC, Mirkoet requested changes
Really minor spelling things, i cant really find anything else

2024-05-29 07:47 UTC, tomseli approved these changes
lgtm 👍

2024-05-29 07:48 UTC, Mirkoet approved these changes
The drawing functions work. for mvp this is enough.

2024-05-29 09:00 UTC, merged